CREATE TABLE DEPT(
    DEPTID NUMBER PRIMARY KEY,
    DEPTNAME VARCHAR(10),
    LOCATION VARCHAR(10)
);

INSERT INTO DEPT VALUES (701, 'CSE', 'Kolkata');
INSERT INTO DEPT VALUES (702, 'IT', 'Mumbai');
INSERT INTO DEPT VALUES (703, 'IT', 'Kolkata');
INSERT INTO DEPT VALUES (704, 'EE', 'Kolkata');
INSERT INTO DEPT VALUES (705, 'ECE', 'Chennai');
INSERT INTO DEPT VALUES (708, 'EE', 'Kolkata');
INSERT INTO DEPT VALUES (710, 'CSE', 'Bengalore');